### ISSUE TITLE
Manhattan Gtk Theme

### ISSUE THREAD

**Issue by RosGtHub** [kartorias1/Hyprland-dotfiles#1]
Hi, could you leave the link to the gtk-theme? Please.  I tried to reply all and at the the end looks like this:
![20221024_23h32m10s_grim](https://user-images.githubusercontent.com/89165766/197633695-76d23c84-7511-4820-906d-6a4812db967a.png)
And how can i set it global? i don't like white apps ( i'm new to this world).

**Comment by lukas0173** [comment]
Hi, sorry for the late reply.
I don't use Gtk theme for eww widget, the icon does not render correctly due to the missing font. You can download the file being attached, unzip to get the font file and paste it into `/usr/share/fonts/TTF`, reboot the machine and enjoy!
[icomooon_font.zip](https://github.com/kartorias1/Hyprland-dotfiles/files/9860843/icomooon_font.zip)

**Comment by lukas0173** [comment]
For application's global theme, you should read through Qt and Gtk on archlinux wiki:
https://wiki.archlinux.org/title/qt
https://wiki.archlinux.org/title/GTK
I'm using LxApperiance for mange Qt themes, currently is Arc-Dark.
Kvantum for Gtk theme, and I set the theme to "Kvantum-Arc-Dark"

**Comment by RosGtHub** [comment]
it's actually all bugged.

**Comment by RosGtHub** [comment]
i tried to reinstall plasma too but it just gives more problems

**Comment by RosGtHub** [comment]
Resolved reading the wiki ahha! Thanks you so much.

Edit: doesn't apply the GTK theme for some reason i tried alot of things mh... i tried to set it manually too  :(.
![20221025_21h58m14s_grim](https://user-images.githubusercontent.com/89165766/197869904-81e126a3-6c1b-404d-9507-97c06d1d09b3.png)
This is what i did.

**Comment by lukas0173** [comment]
Try add this line into `/etc/environment` (as root) 
QT_STYLE_OVERRIDE=kvantum
save and reboot

**Comment by RosGtHub** [comment]
didn't change anything firefox is still white like all the gtk apps they look like this: 
![20221026_16h08m46s_grim](https://user-images.githubusercontent.com/89165766/198048782-810f75d6-e212-4c22-a4aa-448c0e61399d.png)
And when i take the window has a weird behavior i don't know if is normal.

https://user-images.githubusercontent.com/89165766/198060649-5ebdd780-b487-4bf1-bec4-aad4f0565be5.mp4
(even obs is weird looks like not themed at all) Should i reinstall arch? or just find solutions because i don't know how to fix them.Sorry if i'm asking you too much.

**Comment by lukas0173** [comment]
For the firefox theme, you should set the theme manually in firefox settings.
For the tiny window behavior, it's because it is in floating-mode when you drag it. Press Ctrl + space to toggle floating-mode manually, and resize it as you want, then Ctrl+space again to back to normal.

**Comment by RosGtHub** [comment]
And what about others apps like lutris etc..?

**Comment by RosGtHub** [comment]
I FIXED IT! i'm so damnly happy! Thanks you so much for all the help and time spent!.
