### ISSUE TITLE
Hyprland not showing anything

### ISSUE THREAD

**Issue by ItsRedlyXD** [kartorias1/Hyprland-dotfiles#2]
Ohayo!

Whenever I install the packages, and "cp -r * ~/.config". It doesn't show the costumized D.E. Not even the waybar opens!

Hope you can help me!

**Comment by lukas0173** [comment]
hmm the window manager should be working, you will need to config the rest (if needed). You first want to check the key bind in the configuration file in `.config/hypr/hyprland.conf` to see if the corresponding applications are working. Then run `waybar` in the terminal and see what is the output.

**Comment by ItsRedlyXD** [comment]
The keybinds don't work, but I gave already.

Thank you so much for your help! <3
